'use strict';

const actions = require('./actions');
const fs = require('fs');
const readline = require('readline');
const util = require('util');
const utils = require('./utils.js');

const DONT_ASK = 'Don\'t ask.';
const ANSWER_IS_NO = '';

const _questionWireframes = utils.getWireframes();

class _Question {
  constructor(wireframeName) {
    const wireframe = _questionWireframes[wireframeName];
    for (let w in wireframe) {
      this[w] = wireframe[w];
    }
    this.name = wireframeName;
    this.answer = null;
  }

  _isValid() {
    let valid = true;
    if (!this.pattern) { return valid; }
    const regex = RegExp(this.pattern, 'g');
    const result = regex.exec(this.answer);
    if (!result) { valid = false; }
    return valid;
  }

  _prompt(prompt) {
    return new Promise((resolve, reject) => {
      utils.prompt.question(prompt, (answer) => {
        (answer == '') ? this.answer = this.default : this.answer = answer;
        if (this._isValid()) {
          resolve(this);
        } else {
          reject();
        }
      })
    })
  }

  async ask(forPage) {
    await this._ask();
    if (this.action) {
      await actions[this.action.name].run(forPage, this);
    }
    const token = "[[" + this.name + "]]";
    forPage.contents = forPage.contents.replace(token, this.answer);
  }

  async _ask() {
    let prompt = "\n" + this.question;
    if (this.default) {
      prompt += (" (" + this.default + ")");
    }
    prompt += "\n";
    try {
      await this._prompt(prompt);
    } catch(e) {
      console.log("\n" + this.help);
      await this.ask();
    }
    return this;
  }
}

class _Questions {
  constructor(intro) {
    this.intro = intro;
    this.questions = new Object();
  }

  printIntro() {
    if (this.intro == '') { return; }
    console.log(this.intro);
  }

  set introMessage(message) {
    this.intro = message;
  }

  add(question, answer=null) {
    if (_questionWireframes[question] == DONT_ASK) { return; }
    if (!this.questions.hasOwnProperty(question)) {
      this.questions[question] = new _Question(question);
      this.questions[question].answer = answer;
    }
  }

  answer(question, answer) {
    this.questions[question].answer = answer;
  }

  needsAnswers() {
    for (var p in this.questions) {
      if (this.questions[p].answer === null) { return true; }
    }
    return false;
  }
}

class _Page {
  constructor(name, type, sharedQuestions) {
    this.name = name;
    this.type = type;
    this.sharedQuestions = sharedQuestions;
    // The type and name if the interface are also a question.
    this.sharedQuestions.add(type, name);
    let introMessage = `\nQuestions for the ${this.name} ${this.type} page\n` + (`-`.repeat(80));
    this.questions = new _Questions(introMessage);
    this.contents = utils.getTemplate(this.type.toLowerCase());
    const reg = RegExp(utils.TOKEN_RE, 'g');
    let matches;
    while ((matches = reg.exec(this.contents)) != null) {
      if (matches[0].startsWith('[[shared:')) {
        this.sharedQuestions.add(matches[1]);
      } else {
        this.questions.add(matches[1]);
      }
    }
  }

  async askQuestions(extraMessage) {
    if (this.sharedQuestions.needsAnswers()) {
      // extraMessage is proxy for whether this is a first call or
      // one generated by an action. Not ideal, but it's the best
      // currently available.
      if (extraMessage) {
        this.sharedQuestions.introMessage = "More shared questions found.\n" + (`-`.repeat(28))
      }
      await this._askQuestions(this.sharedQuestions);
    }
    if (this.questions.needsAnswers()) {
      if (extraMessage) {
        let len = extraMessage.length;
        extraMessage = extraMessage + '\n' + (`-`.repeat(len));
        this.questions.introMessage = extraMessage;
      }
      await this._askQuestions(this.questions);
    }
  }

  async _askQuestions(questionObject) {
    const questions = questionObject.questions;
    if (questionObject.needsAnswers()) {
      questionObject.printIntro();
    } else {
      return;
    }
    for (let q in questions) {
      if (questions[q].answer) { continue; }
      await questions[q].ask(this);
    }
  }

  render() {
    const reg = RegExp(utils.TOKEN_RE);
    let matches;
    let answer;
    while ((matches = reg.exec(this.contents)) != null) {
      if (matches[0].startsWith('[[shared:')) {
        answer = this.sharedQuestions.questions[matches[1]].answer;
      } else {
        answer = this.questions.questions[matches[1]].answer
      }
      if (answer == DONT_ASK) { continue; }
      if (answer === null) { continue; }
      this.contents = this.contents.replace(matches[0], answer);
    }
  }

  write() {
    this.render();
    let outFolder = utils.OUT + '/' + this.sharedQuestions.name + '/';
    if (!fs.existsSync(outFolder)) { fs.mkdirSync(outFolder); }
    let outPath = outFolder + this.sharedQuestions.name + "_" + this.name + "_" + this.type + ".html";
    fs.writeFileSync(outPath, this.contents);
  }
}

module.exports.Page = _Page;
module.exports.Questions = _Questions;
