[
    Constructor(DOMString family, (DOMString or ArrayBuffer or ArrayBufferView) source, optional FontFaceDescriptors descriptors)
] interface ConstructorArgs {
    [RaisesException=Setter, SetterCallWith=ExecutionContext] attribute DOMString family;
};