[
    Exposed=Window,
    ActiveScriptWrappable
] interface Constructor1Arg {
    constructor(DOMString family);
    [RaisesException=Setter, SetterCallWith=ExecutionContext] attribute DOMString family;
};