[
    Exposed=Window,
    ActiveScriptWrappable
] interface ConstructorSeqArgs : CSSStyleValue {
    Constructor(sequence<CSSUnparsedSegment> members);
    readonly attribute unsigned long length;
};
