interface EventHand : EventTarget {
    [RuntimeEnabled=OTEExperimental] attribute EventHandler ondevicechange;
    attribute EventHandler onconnect;
    [MeasureAs=GenericSensorOnError] attribute EventHandler onerror;
};
