interface EventHand : EventTarget {
    attribute EventHandler onconnect;
    [MeasureAs=GenericSensorOnError] attribute EventHandler onerror;
    [RuntimeEnabled=RTEExperimental] attribute EventHandler ondevicechange;
};
