typedef (CSSNumericValue or CSSKeywordish) ScrollTimelineContainerBasedOffset;
typedef (ScrollTimelineContainerBasedOffset or ScrollTimelineElementBasedOffset) ScrollTimelineOffset;

[
    RuntimeEnabled=ScrollTimeline,
    Exposed=Window
] interface ScrollTimeline : AnimationTimeline {
    [CallWith=Document, RaisesException, MeasureAs=ScrollTimelineConstructor] constructor(optional ScrollTimelineOptions options = {});
    readonly attribute Element? source;
    readonly attribute ScrollDirection orientation;
    readonly attribute FrozenArray<ScrollTimelineOffset> scrollOffsets;
};
