interface Properties {
    attribute FontFaceLoadStatus status;
    OffscreenRenderingContext? getContext(OffscreenRenderingContextType contextType, optional CanvasContextCreationAttributesModule attributes = {});
};