interface MethodArgs : EventTarget {
    [RaisesException] boolean check(DOMString font, optional DOMString text = " ");
    [RaisesException] boolean checks();
    [RuntimeEnabled=RTEExperimental] readonly attribute boolean raw;
};
