 interface MethodMultiReturns {
    readonly attribute unsigned long length;
    getter Element? (unsigned long index);
    [ImplementedAs=NamedGetter] getter (HTMLCollection or Element)? namedItem(DOMString name);
    [Custom] (HTMLCollection or Element)? item(optional DOMString nameOrIndex);
};