[
    ActiveScriptWrappable
] interface mixin MixinBody {
    [RaisesException] readonly attribute boolean bodyUsed;
    [CallWith=ScriptState, NewObject, RaisesException] Promise<ArrayBuffer> arrayBuffer();
    [CallWith=ScriptState, NewObject, RaisesException] Promise<Blob> blob();
    [CallWith=ScriptState, NewObject, RaisesException] Promise<FormData> formData();
    [CallWith=ScriptState, NewObject, RaisesException] Promise<JSON> json();
    [CallWith=ScriptState, NewObject, RaisesException] Promise<USVString> text();
};

Destination includes MixinBody;