[
    Exposed=Window,
    ImplementedAs=DOMWindowCSS
] partial namespace PartialNamespaceName {
    [CallWith=ExecutionContext] boolean supports(DOMString property, DOMString value);
    [CallWith=ExecutionContext] boolean supports(DOMString conditionText);
    DOMString escape(DOMString ident);
};
