[
    Exposed=(Window,Worker,AudioWorklet)
] interface Event {
    constructor(DOMString type, optional EventInit eventInitDict);
    readonly attribute DOMString type;

    [Measure] void stopPropagation();
};
