interface Properties {
    [RuntimeEnabled=RTEExperimental] attribute FontFaceLoadStatus status;
    [RuntimeEnabled=RTEExperimental] attribute EventHandler onstart;

    [RuntimeEnabled=RTEExperimental] readonly attribute boolean raw;
};