interface Properties {
    [RuntimeEnabled=RTEExperimental] attribute FontFaceLoadStatus status;
    [RuntimeEnabled=RTEExperimental] readonly attribute boolean raw;
    [RuntimeEnabled=RTEExperimental] readonly maplike<DOMString, object>;
};